### ISSUE TITLE
Obtaining Kalendae object of instance created via class auto-kal

### ISSUE THREAD

**Issue by wehadfun** [ChiperSoft/Kalendae#102]
If you use the code at the beginning of the readme <div class=auto-kal></div> to create a Kalendae how would you find out what the selected date is or add an event handler to it.

Is there some way to get the Kalendae object?

**Comment by ChiperSoft** [comment]
I'm afraid there's no way to obtain the kalendae object when it's auto-created. the object is not attached to anything in a public scope.
