### ISSUE TITLE
Problem with short date formats

### ISSUE THREAD

**Issue by baywind** [ChiperSoft/Kalendae#106]
I have a text field containing date in format 'DD.MM'.
If I attach Kalendae to it I get a calendar for year 1900. Well, that's expected behaviour, so I add special options to initialization:

new Kalendae.Input('shortDateField', {
	format:'DD.MM',
	selected:Kalendae.moment('2013-10-08')
});

Now I get correct calendar, but selected date is not highlighted.

I tried debugging and found that Kalendae object still contains date in year 1900.

**Comment by ChiperSoft** [comment]
This isn't an issue in Kalendae, but rather with how Moment parses dates. I don't see a way we could address this.
