### ISSUE TITLE
Preselected date next year fails setting up the calendar

### ISSUE THREAD

**Issue by peternic** [ChiperSoft/Kalendae#116]
Hi, first of all, thanks for a great calendar to work with :-)

I have met on a problem when I set the **selected** option to a date later than february next year.

For example:
This does not work, also for all greater dates. (Earlier dates is ok) 
```
var calendar = new Kalendae.Input(input, {
            selected: "01.02.2014",
            weekStart: 1,
            direction: 'today-future',
            dayOutOfMonthClickable: true,
            format: "DD.MM.YYYY"
        });
```
It is the makeSelectedDateVisible that fails, since the diff does not return 0, and it seems that the viewStartDate is not set, and then it fails on "cannot call add on undefined. 
```
makeSelectedDateVisible: function (date) {
            outOfViewMonth = moment(date).date('1').diff(this.viewStartDate,'months');

            if(outOfViewMonth < 0){
                this.viewStartDate.subtract('months',1);
            }
            else if(outOfViewMonth > 0 && outOfViewMonth >= this.settings.months){
                this.viewStartDate.add('months',1);
            }
        }
```

I added a check on this.viewStartDate on at our side, and this seems to work for us, but not sure if this is the best way to solve this problem.

```
makeSelectedDateVisible: function (date) {
            outOfViewMonth = moment(date).date('1').diff(this.viewStartDate,'months');

            if(outOfViewMonth < 0 && this.viewStartDate){
                this.viewStartDate.subtract('months',1);
            }
            else if(outOfViewMonth > 0 && outOfViewMonth >= this.settings.months && this.viewStartDate){
                this.viewStartDate.add('months',1);
            }
        }
```

I have created two fiddles that demonstrate the problem and how my fix works:
Where it does not work: http://jsfiddle.net/2qAg8/
Where it works: http://jsfiddle.net/dYmWt/

Please let me know if this is the way to do it or if there is a better way, and I can provide you with a pullrequest :-)

Thanks again!

**Comment by ChiperSoft** [comment]
I think this may have been addressed in 0.5.4, there were some issues with calling subtract
