### ISSUE TITLE
today-past & past not able to scroll forward to current month

### ISSUE THREAD

**Issue by tregota** [ChiperSoft/Kalendae#123]
I'm using today-past and when Kalendae chooses whether to show forward scrolling arrows for both month and year it misses by one month. So even if it starts on the right month once you scroll back a bit you cannot get back. I just changed the comparison for disableNextMonth and disableNextYear to less than 1 and less or equal to 1 instead of 0. Didn't delve deeper than that. works for me. Great calendar by the ways. Thanks.

**Comment by chrisamaral** [comment]
+1
