### ISSUE TITLE
How can I restrict user to select the date range from current year only.

### ISSUE THREAD

**Issue by sampatbadhe** [ChiperSoft/Kalendae#137]
I need the calendar to allow user to select the date form this year only.
is this possible?

**Comment by ChiperSoft** [comment]
Yes, you can create a blackout function that returns false for any date outside of the current year.

```js
function (date) {return date.getYear() === (new Date()).getYear();}
```

**Comment by sampatbadhe** [comment]
Thanks :) :+1:
