### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by daniel-aranda** [ChiperSoft/Kalendae#138]
Hey, Thank You for the library. I want to implement a standalone Calendar library and this seems to be a good choice, however I figured that this does not have unit tests, so I'm wondering if there are any plans to add unit tests to this project?

Thank You,

**Comment by ChiperSoft** [comment]
Plans, yes. There have been plans for two years. However, it wasn't originally written to be testable, so doing so will require a fairly significant overhaul.  I've been wanting to do a rewrite for a 2.0 release (technically a 1.0), but there's always been more important work to do.

**Comment by daniel-aranda** [comment]
Ok, thank you. @ChiperSoft
