### ISSUE TITLE
Multiple month view not obeying viewStartDate for February (or current month maybe?)

### ISSUE THREAD

**Issue by yehudahkay** [ChiperSoft/Kalendae#139]
Hi I am trying this
```
$('#calendar').kalendae({
                   mode: 'multiple', 
                   months: 3,
                   viewStartDate: '2/1/2015'
               });
```
If viewStartDate is set to a different month it will work. But if it is not set or set to February (current month) then the months shown are January, February, March. I see the same on the demo http://chipersoft.com/Kalendae/

**Comment by yehudahkay** [comment]
I fixed this by using 

```
$('#calendar').kalendae({
                   mode: 'multiple', 
                   months: 3,
                   direction: 'today-future'
               });
```
Perhaps this is intentional? Although I'm not sure why it would work one way for the current month and different way for other months

**Comment by ChiperSoft** [comment]
Yes, it is intentional. Multi-month views always center on the viewStartDate (or start on it for calendars showing an even number of months).  The reason today-future changes this behavior is because the user would not be able to select a day prior to the current month, so there's no reason to show them that month. It works the opposite for today-past.

**Comment by yehudahkay** [comment]
Actually viewStartDate isn't centered when it is in the future rather it is the first month, so I'm not 100% sure I  understood.

**Comment by ChiperSoft** [comment]
It centers when there is no direction defined. It aligns against an edge when future or past directions are used.

**Comment by yehudahkay** [comment]
Hi Chipersoft, maybe I didn't explain 100%. If you use  viewStartDate: '3/1/2015' it will start from May and move forward. If you use  viewStartDate: '2/1/2015' it will put February in the middle. That's what I thought was inconsistent.

**Comment by ChiperSoft** [comment]
> it will start from May 

May? Not March?

**Comment by yehudahkay** [comment]
Sorry, March :-) I don't live in the US anymore

**Comment by ChiperSoft** [comment]
Oh, I see.  I don't remember if that was the intent, but I'm ok with keeping it that way.
