### ISSUE TITLE
Tag 0.5.1 release

### ISSUE THREAD

**Issue by cgunther** [ChiperSoft/Kalendae#144]
Could you tag the 0.5.1 release (c5d0d2b9e3c64240dd556a5f383026b9b8465b31)?

I believe that should make it visible to Bower, and in turn, [Rails Assets](https://rails-assets.org/).

Thanks!

**Comment by ChiperSoft** [comment]
Done.

**Comment by cgunther** [comment]
Awesome, thank you!
