### ISSUE TITLE
subscribe on change, action always undefined

### ISSUE THREAD

**Issue by gonace** [ChiperSoft/Kalendae#145]
Hi
I'm using subscribe on change and trigger a ajax call when a range is selected (meaning when two dates is selected)

However I need to set the initial range when the page is loaded, I figured that I could use action to no trigger an ajax call when using setSelected but the "action" argument is always undefined.

So the change is triggered and the ajax call is called. Why are the action always undefined?

**Comment by ChiperSoft** [comment]
Honestly, I don't know why the example in the readme shows an action argument, there's nothing in the source that could ever populate that argument and nothing in the docs to indicate what that value could hold.  Perhaps that was an idea that I had explored and then changed my mind about.

I'll update the readme to remove that.
