### ISSUE TITLE
'change' event fires when Kalendae is opening

### ISSUE THREAD

**Issue by mickeyvip** [ChiperSoft/Kalendae#146]
I am not this is a bug, but it feels unnatural.

I have a preset date range in an `input` field. Clicking on it opens the `Kalendae`. I can see that the `'change'` event is fired twice.

I would expect no event firing while the `Kalendae` is opening and being initialized with preset dates.

**Comment by aaronjensen** [comment]
I'd say this is a bug. It fires as the old date range is removed, then the new one is added. For us, it fires several times, I think 4 in total. Two to remove the old range and two more to add the new range. It's only on the last that the dates are actually accurate.

**Comment by reintroducing** [comment]
Agreed, just ran into this and it definitely seems like a bug.

**Comment by ChiperSoft** [comment]
I don't think this is something I can address with the current way that kalendae is written. The event model was somewhat immature and kind of grafted on as people needed more functionality. If I ever get around to a rewrite then perhaps I can address it then.  Sorry.

**Comment by aaronjensen** [comment]
To work around this we did:

```
    Kalendae.util.removeEvent(inputElement, 'focus', picker._events.inputFocus)
    $(inputElement).on('focus', () => picker.show())
```
