### ISSUE TITLE
Disabling several dates

### ISSUE THREAD

**Issue by bcgoodmate** [ChiperSoft/Kalendae#151]
I want to disable a range of dates like the format below:
disable[0] = { start: '2015-07-03', end: '2010-07-11' };
disable[1] = { start: '2010-07-17', end: '2010-07-20' };
disable[2] = { start: '2010-08-01', end: '2010-08-02' };

How can I do this using Kalendae blackout function?

**Comment by ChiperSoft** [comment]
This is dry coded and might have errors, but I believe it should do the job.

```js
function (date) {
  var ok = true;
  disable.forEach(function (d) {
    if (!ok || date >= (new Date(d.start)) && date <= (new Date(d.end))) ok = false;
  }
  return ok;
}
```

**Comment by bcgoodmate** [comment]
The code below is working good except to dates that are in between different months. 

var disable = [];
		
disable.push({ start: '2015-06-28', end: '2010-06-29' });
disable.push({ start: '2015-06-30', end: '2010-07-01' }); // Dates in between different months doesn't works.
disable.push({ start: '2015-07-03', end: '2010-07-05' });
disable.push({ start: '2010-07-17', end: '2010-07-20' });
disable.push({ start: '2010-08-01', end: '2010-08-15' });

var mo = Kalendae.moment,
	i=disable.length,
	dd = Kalendae.moment(date).date(),
	mm = Kalendae.moment(date).month(),
	start,
	stop;

while (i--) {
	start = mo(disable[i].start);
	stop = mo(disable[i].end);
	
	if (mm == start.month() && mm == stop.month() && dd >= start.date() && dd <= stop.date()) return true;
}
return false; 

credits to: https://github.com/ChiperSoft/Kalendae/issues/18
