### ISSUE TITLE
selecting a date is selecting previous date if moment with timezone is used

### ISSUE THREAD

**Issue by tgvrssanthosh** [ChiperSoft/Kalendae#152]
When i use moment with timezone and uses kalandae.js (kalandae.standalone is working fine), then selecting a date is selecting the previous date.

please open the following fiddle and try to select any date..
http://jsfiddle.net/mm0p6do8/

**Comment by ChiperSoft** [comment]
I'm not able to reproduce this with your fiddle (it probably depends on the local timezone and time), however it does not surprise me that you are having problems.  Timezones are a nightmare, I do not recommend trying to make Kalendae work with anything other than the user's local TZ.

**Comment by adion** [comment]
@tgvrssanthosh @ChiperSoft You have to change the timezone in your system to reproduce.

**Comment by adion** [comment]
> Timezones are a nightmare, I do not recommend trying to make Kalendae work with anything other than the user's local TZ.

> Kalendae is an attempt to do something that nobody has yet been able to do: make a date picker that doesn't suck. 

I'd say proper timezone support should be core to a **Calendar** library. Are you effectively saying you have no plans to support moment-timezone?

**Comment by ChiperSoft** [comment]
Kalendae is not a calendar library, it's a date picker. It has one job, to display a range of days and let the user select one or more.  You don't need timezones when you're working with whole days.

It was never written with the intent of handling fractions of days. If your use case requires a date picker that is aware of the international date line, then Kalendae is probably not for you.

**Comment by adion** [comment]
Duly noted. We'll find an alternative.
