### ISSUE TITLE
Moment deprecation warning

### ISSUE THREAD

**Issue by reintroducing** [ChiperSoft/Kalendae#159]
I'm using my own version of moment and sometimes I'm seeing this warning come up when going through months in Kalendae.

```
Deprecation warning: moment().subtract(period, number) is deprecated. Please use moment().subtract(number, period).
```

I can't quite place how to reproduce this exactly but I'm sure its coming from Kalendae as it only happens when using a calendar.  Just wanted to give you a heads up so you can maybe put a version check in for that depending on when that changed and what your expectation of the API from moment is.

**Comment by ChiperSoft** [comment]
I've just pushed out version 0.5.5, which includes this fix.

**Comment by reintroducing** [comment]
awesome, appreciate the quick reply!
