### ISSUE TITLE
Different mode support for inputs?

### ISSUE THREAD

**Issue by reintroducing** [ChiperSoft/Kalendae#160]
Is it possible to use a mode other than 'single' when using an input? Currently what I'm seeing is that if I change the mode to 'multi' or 'range' the input closes right away and I can't make any more selections.

On a related note, it would be a nice option to be able to control when/how the calendar opens/closes when used in Input mode.  I'd like to add an animation to open/close using CSS transitions but right now I can't do that since the display is just set to 'none' on close.

**Comment by ChiperSoft** [comment]
Sorry but I'm not able to reproduce this. I had no issue setting an input to `mode:'multiple'` or `mode:'range'`.  Could you produce a fiddle that demonstrates the issue?
