### ISSUE TITLE
[Feature] Dropdown to Select Month/Year

### ISSUE THREAD

**Issue by jpgilchrist** [ChiperSoft/Kalendae#163]
Love the idea of this, but if I cannot provide a dropdown to select month and year, I cannot use it. 

Thoughts?

**Comment by pfiller** [comment]
@jpgilchrist When participating in open source discussions, it's really important to remember that many projects are maintained by people in their spare time. Your issue basically says "I can't use this library unless it's different." Imagine reading that about something you built!

There are really two options for your scenario (wanting dropdowns to select month and year):

**Option 1: Use a library that has the features you want.** Something like [jQuery UI's date picker](https://jqueryui.com/datepicker/#dropdown-month-year) already implements the feature you want. I'm sure there are others!

**Option 2: Volunteer!** Open an issue and ask if this is a feature that @ChiperSoft would continue merging. If he says "sure", then build it! If he says "no", fork it and build it anyway. Kalendae is released under the MIT software license and you can do whatever you want with it. Maybe someone else would find your version useful. Wouldn't that be neat?

I hope that helps a bit. Open source work can be a bit of a thankless world. Always assume that people are doing their best!

**Comment by jpgilchrist** [comment]
@pfiller I apologize for sounding offensive. 

1. I already know you are working on this part time and have a family and a job. I read your README. 

2. This was sort of my intro to, what's the road map here. Any chance this is planned at some point?

Apparently, it is not planned. However, you did not give me a good sense of direction you are taking this project and if that is something you want. I should have been a bit wordier with my question. At the time, I was busy trying to get many things done. 

I found an alternative solution (although I really wanted a moment.js backed datepicker, my other solution will suffice) and will be continuing with that. However, at some point (when I have time) I may come back to this, fork it, and issue a pull request.
