### ISSUE TITLE
How to let Kalendae use the latest moment.js library version?

### ISSUE THREAD

**Issue by meglio** [ChiperSoft/Kalendae#172]
I noticed Kalenda uses out-of-date version of Moment.
How would I let it use the latest moment.js version instead?
Thanks.

**Comment by zawiasam** [comment]
you have two builds
kalendae.standalone.js - with included Moment
kalendae.js - without Moment - will be used implementation provided by you

**Comment by meglio** [comment]
Thanks, it worked like that.
