### ISSUE TITLE
Language conversion of calander

### ISSUE THREAD

**Issue by bcsbcs109** [ChiperSoft/Kalendae#179]
Is it possible to convert the calander in french and german language as per the requirement

**Comment by ChiperSoft** [comment]
All strings in Kalendae come from Moment.js, so you can setup Moment's localization with the language you want.

**Comment by bcsbcs109** [comment]
hello Jarvis,


Thats really very cool but it would be helpful if you give me small Example
for the implementation.

**Comment by ChiperSoft** [comment]
```html
<script src="moment.js"></script>
<script src="locale/fr.js"></script>
<script>
  moment.locale('fr');  // Set the default/global locale
  // ...
</script>
<script src="kalendae.js"></script>
```
Note that you would use `kalendae.js`, not `kalendae.standalone.js`.

You can find more info in Moment's docs. http://momentjs.com/docs/#/i18n/loading-into-browser/

**Comment by bcsbcs109** [comment]
hello Jarvis,


Thank you very much it is working perfectly right that's really nice of you

**Comment by bcsbcs109** [comment]
hey Jarvis,

i just write a code in mvc i put try catch block in the controller but i am
not able to put that in scriptt->common.js
will please tell how i put try catch in java Script

**Comment by bcsbcs109** [comment]
hello jarvis,


Can you please tell that how to use blackout function in kalendae if i am
using it in this form.


$("#CalanderKalande1").kalendae();



please let me know the contex.


Regards,

Dhruv Jaiswal

**Comment by ChiperSoft** [comment]
The blackout function works like array.filter(). You define a function which receives a date and returns a boolean. If the return is truthy then the date will be allowed, if the return is falsey then the date will be blocked.

There's a couple examples in the index.html file that comes with Kalendae.
