### ISSUE TITLE
Correct calendar if out-of-month is not displayed

### ISSUE THREAD

**Issue by mcrundo** [ChiperSoft/Kalendae#182]
Using multi-select, having the out-of-month dates displayed is not very intuitive UX. It's confusing when two dates fill up on one event. It makes sense if you think about it, but it is still confusing to users. 

Could there be a way to hide out-of-month without affecting the accuracy of the calendar? Currently, if that class is set to `display:none` it causes the days on a calendar to be incorrect.

**Comment by ChiperSoft** [comment]
Have you tried setting them to `visibility:hidden`?

**Comment by mcrundo** [comment]
@ChiperSoft good call, that works. Thanks!
