### ISSUE TITLE
Allows selecting blackout days when using range mode

### ISSUE THREAD

**Issue by dudevon** [ChiperSoft/Kalendae#63]
When using the `mode: 'range'` option alongside blackout dates, the range can be selected through the blackout dates.

Here's an example: http://jsfiddle.net/KBSd9/

**Comment by ChiperSoft** [comment]
This is expected behavior for range mode, as range only supports a single start and stop date.  If the range excluded dates then it wouldn't be a range, it would be a multi-select.
